name: 100% Coverage

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - run: uv sync --group test

      - name: Run tests with coverage
        run: uv run --package hundredandten-engine coverage run --branch --source=hundredandten.engine -m pytest

      - name: Check coverage
        run: uv run --package hundredandten-engine coverage report --fail-under=100
