name: 100% Coverage

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - hundredandten-engine
          - hundredandten-automation
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - run: uv sync --locked --all-groups --package ${{ matrix.package }}

      - name: Run tests with coverage
        working-directory: packages/${{ matrix.package }}
        run: uv run --package ${{ matrix.package }} coverage run -m pytest

      - name: Check coverage
        working-directory: packages/${{ matrix.package }}
        run: uv run --package ${{ matrix.package }} coverage report
