name: Publish (Test)

on:
  push:

jobs:
  publish:
    environment: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Build and Publish to Test PyPI
        run: |
          uv build --wheel --package hundredandten-deck
          uv build --wheel --package hundredandten-engine
          uv build --wheel --package hundredandten-state
          uv build --wheel --package hundredandten-automation-naive
          uv build --wheel --package hundredandten-automation-engineadapter
          uv publish --index testpypi
