name: Publish (Test)

on:
  push:
    branches-ignore:
      - main

jobs:
  publish:
    # - run: echo "latest_tag=$(git describe --always --tags)" >> $GITHUB_ENV
    uses: seamuslowry/workflows/.github/workflows/publish_python.yml@main
    with:
      repo: testpypi
      release-version: "${{ git describe --always --tags }}-${{ github.run_attempt }}"
    secrets:
      py_pi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
